apiVersion: v2
name: cluster-autoscaler-crossplane-resources
description: Crossplane Resources for Cluster Autoscaler
version: 0.1.0
home: https://github.com/giantswarm/cluster-autoscaler-crossplane-resources
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
annotations:
  application.giantswarm.io/team: tenet
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
